# Site settings
title: Data-Centric Design
description: Using data as a design material
baseurl: "/lab" # the subpath of your site, e.g. /blog
url: "https://datacentricdesign.org" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jacky Bourgeois
user_description:
email: jacky@datacentricdesign.org
twitter_username: jackybourgeois
github_username:  jackybourgeois
gplus_username:  
disqus_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Us
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
